getopt_old.m:027: In clause for predicate `main'/2:
getopt_old.m:027:   in argument 2 of call to predicate `io.format'/4:
getopt_old.m:027:   in list element #1:
getopt_old.m:027:   in unification of argument
getopt_old.m:027:   and term `s(ErrorMsg)':
getopt_old.m:027:   type error in argument of functor `s'/1.
getopt_old.m:027:   Argument 1 (ErrorMsg) has type
getopt_old.m:027:     [38;5;203mgetopt.option_error(getopt_old.option),[39;49m
getopt_old.m:027:   expected type was
getopt_old.m:027:     [38;5;40mstring.[39;49m
getopt_old.m:027:   [38;5;226mOne possible reason for the error is that the signatures of[39;49m
getopt_old.m:027:   [38;5;226mthe option processing predicates in the `getopt' module[39;49m
getopt_old.m:027:   [38;5;226mhave changed recently. Errors are now returned in a[39;49m
getopt_old.m:027:   [38;5;226mstructured form, which can be converted to a string by[39;49m
getopt_old.m:027:   [38;5;226mcalling the `option_error_to_string' function.[39;49m
